const ImageLinks = {
  clock: require('../assets/images/clock.png'),
  gg: require('../assets/images/gg.png'),
  menu: require('../assets/images/menu.png'),
  plusSquare: require('../assets/images/plusSquare.png'),
  gift: require('../assets/images/gift.png'),
  heart: require('../assets/images/heart.png'),
  pinkClock: require('../assets/images/pinkClock.png'),
  likeOutlined: require('../assets/images/likeOutlined.png'),
  user1: require('../assets/images/user1.png'),
  user2: require('../assets/images/user2.png'),
  likeFilled: require('../assets/images/likeFilled.png'),
  message: require('../assets/images/message.png'),
  threeDots: require('../assets/images/threeDots.png'),
  star: require('../assets/images/star.png'),
  block: require('../assets/images/block.png'),
  lock: require('../assets/images/lock.png'),
  chat: require('../assets/images/chat.png'),
  help: require('../assets/images/help.png'),
  about: require('../assets/images/about.png'),
  trash: require('../assets/images/trash.png'),
  logout: require('../assets/images/logout.png'),
};

export default ImageLinks;
